export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGOUT_USER = "LOGOUT_USER";

export const  RECEIVE_GAMES_REQUEST = "RECEIVE_GAMES_REQUEST"
export const  RECEIVE_GAMES_SUCCESS = "RECEIVE_GAMES_SUCCESS"
export const  RECEIVE_GAMES_FAILURE = "RECEIVE_GAMES_FAILURE"